package pkg

import "google.golang.org/protobuf/compiler/protogen"

func GenerateHeader(g *protogen.GeneratedFile, name protogen.GoPackageName) {
  g.P("// Generated by errorbuilder. DO NOT EDIT")
  g.P()
  g.P("package ", name)
}